#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs';
import type { PackageHash } from '../shared';
import { calculateSHA256 } from './utils';

/**
 * Generate a pool path for a package (standard Debian repository structure)
 * Example: pool/main/p/proton-mail/proton-mail_1.9.1_amd64.deb
 */
function generatePoolPath(packageName: string, version: string): string {
  const firstLetter = packageName.charAt(0);
  const filename = `${packageName}_${version}_amd64.deb`;
  return `pool/main/${firstLetter}/${packageName}/${filename}`;
}

function generatePackagesFile(packageData: PackageHash[]): string {
  let content = '';

  for (const pkg of packageData) {
    // Map product to package name
    const packageName = pkg.product === 'mail' ? 'proton-mail' : 'proton-pass';
    const description =
      pkg.product === 'mail'
        ? 'Proton Mail - Secure and private email'
        : 'Proton Pass - Secure password manager';

    // Generate relative pool path instead of full URL
    const poolPath = generatePoolPath(packageName, pkg.version);

    content += `Package: ${packageName}
Version: ${pkg.version}
Architecture: amd64
Maintainer: Proton AG <opensource@proton.me>
Filename: ${poolPath}
Size: ${pkg.size}
SHA256: ${pkg.sha256}
Section: utils
Priority: optional
Homepage: https://proton.me/
Description: ${description}

`;
  }

  return content.trim();
}

function generateReleaseFile(packagesContent: string): string {
  const packagesHash = calculateSHA256(packagesContent);
  const packagesSize = Buffer.byteLength(packagesContent, 'utf8');

  // Generate architecture-specific Release content
  const archReleaseContent = `Archive: stable
Component: main
Origin: Proton Repository Proxy
Label: Proton Apps
Architecture: amd64
`;

  const archReleaseHash = calculateSHA256(archReleaseContent);
  const archReleaseSize = Buffer.byteLength(archReleaseContent, 'utf8');

  return `Origin: Proton Repository Proxy
Label: Proton Apps
Suite: stable
Codename: stable
Components: main
Architectures: amd64
Date: ${new Date().toUTCString()}
Description: Proxy repository for Proton applications
Acquire-By-Hash: no

SHA256:
 ${packagesHash} ${packagesSize} main/binary-amd64/Packages
 ${archReleaseHash} ${archReleaseSize} main/binary-amd64/Release
`;
}

function generateArchReleaseFile(): string {
  return `Archive: stable
Component: main
Origin: Proton Repository Proxy
Label: Proton Apps
Architecture: amd64
`;
}

function main(): void {
  console.log('📦 Generating APT repository metadata...');

  // Read hash data
  const packageData: PackageHash[] = JSON.parse(readFileSync('package-hashes.json', 'utf8'));

  // Generate APT files
  const packagesContent = generatePackagesFile(packageData);
  const releaseContent = generateReleaseFile(packagesContent);
  const archReleaseContent = generateArchReleaseFile();

  // Note: url-mapping.json is generated by calculate-links.ts (separate job)

  // Sauvegarder
  writeFileSync('packages-content.txt', packagesContent);
  writeFileSync('release-content.txt', releaseContent);
  writeFileSync('arch-release-content.txt', archReleaseContent);

  console.log('✅ APT metadata generated successfully');
  console.log(`📄 Packages file: ${packagesContent.length} bytes`);
  console.log(`📄 Release file: ${releaseContent.length} bytes`);
  console.log(`📄 Arch Release file: ${archReleaseContent.length} bytes`);
}

main();
