name: Update Repository Metadata

on:
  schedule:
    # Daily at 4 AM UTC
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      force_descriptors:
        description: "Force descriptor recalculation"
        type: boolean
        default: false
      force_apt:
        description: "Force APT metadata regeneration"
        type: boolean
        default: false
  push:
    paths:
      - ".github/workflows/update-metadata.yml"
      - "src/github/**"

env:
  NODE_VERSION: "22"
  CACHE_PREFIX: "update-metadata"
  PROTON_CACHE_DIR: /tmp/proton-api-cache
  PROTON_CACHE_KEY: proton-files-${{ github.run_id }}
  APT_OUTPUT_DIR: /tmp/apt-metadata
  APT_CACHE_KEY: apt-metadata-${{ github.run_id }}

jobs:
  # ============================================================================
  # Security: Verify repository (prevents workflow from running on forks)
  # ============================================================================

  verify-repository:
    runs-on: ubuntu-latest
    name: Verify repository
    if: github.repository == 'Proton-Makers/proton-repo-proxy'
    steps:
      - name: Repository check
        run: |
          echo "✅ Running in authorized repository: ${{ github.repository }}"
          echo "🔐 Repository verified, proceeding with workflow..."

  # ============================================================================
  # Phase 1: Parallel checks
  # ============================================================================

  check-proton-versions:
    runs-on: ubuntu-latest
    name: Check Proton versions
    needs: [verify-repository]
    outputs:
      mail_version: ${{ steps.extract.outputs.MAIL_VERSION }}
      pass_version: ${{ steps.extract.outputs.PASS_VERSION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure cache directory
        run: mkdir -p ${{ env.PROTON_CACHE_DIR }}

      - name: Download Proton API responses
        run: pnpm ci:check-proton-versions:download
        env:
          PROTON_CACHE_DIR: ${{ env.PROTON_CACHE_DIR }}

      - name: Validate API responses
        run: pnpm ci:check-proton-versions:validate
        env:
          PROTON_CACHE_DIR: ${{ env.PROTON_CACHE_DIR }}

      - name: Extract latest versions
        id: extract
        run: pnpm ci:check-proton-versions:versions
        env:
          PROTON_CACHE_DIR: ${{ env.PROTON_CACHE_DIR }}

      - name: Cache Proton API files
        id: cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.PROTON_CACHE_DIR }}
          key: ${{ env.PROTON_CACHE_KEY }}

      - name: Display results
        run: |
          echo "🔍 Version Check Results:"
          echo "📦 Proton Mail: ${{ steps.extract.outputs.MAIL_VERSION }}"
          echo "📦 Proton Pass: ${{ steps.extract.outputs.PASS_VERSION }}"
          echo "💾 API files cached: ${{ env.PROTON_CACHE_KEY }}"

  check-kv-caches:
    runs-on: ubuntu-latest
    name: Check KV caches
    needs: [verify-repository]
    outputs:
      apt_mail_version: ${{ steps.check.outputs.apt_mail_version }}
      apt_pass_version: ${{ steps.check.outputs.apt_pass_version }}
      descriptors_missing: ${{ steps.check.outputs.descriptors_missing }}
      reasons: ${{ steps.check.outputs.reasons }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: whoami

      - name: Check cache status
        id: check
        run: pnpm ci:check-kv-caches
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Display results
        run: |
          echo "🔍 Cache Check Results:"
          echo "📦 APT Mail version: ${{ steps.check.outputs.apt_mail_version }}"
          echo "📦 APT Pass version: ${{ steps.check.outputs.apt_pass_version }}"
          echo "🔢 Descriptors missing: ${{ steps.check.outputs.descriptors_missing }}"
          if [ -n "${{ steps.check.outputs.reasons }}" ]; then
            echo "📝 Reasons: ${{ steps.check.outputs.reasons }}"
          fi

  # ============================================================================
  # Phase 2: Update package descriptors (if needed)
  # ============================================================================

  update-descriptors:
    runs-on: ubuntu-latest
    name: Update package descriptors
    needs: [check-proton-versions, check-kv-caches]
    if: |
      needs.check-proton-versions.outputs.mail_version != needs.check-kv-caches.outputs.apt_mail_version ||
      needs.check-proton-versions.outputs.pass_version != needs.check-kv-caches.outputs.apt_pass_version ||
      needs.check-kv-caches.outputs.descriptors_missing == 'true' ||
      inputs.force_descriptors == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: whoami

      - name: Restore Proton API cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.PROTON_CACHE_DIR }}
          key: ${{ env.PROTON_CACHE_KEY }}

      - name: Download and calculate descriptors
        run: pnpm ci:update-descriptors
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROTON_CACHE_DIR: /tmp/proton-api-cache

      - name: Summary
        run: |
          echo "✅ Package descriptors updated"
          if [ -f /tmp/proton-packages/package-descriptors.json ]; then
            echo "📊 Descriptor file size: $(du -h /tmp/proton-packages/package-descriptors.json | cut -f1)"
          fi

  # ============================================================================
  # Phase 3: Update format-specific metadata (parallel)
  # ============================================================================

  update-apt:
    runs-on: ubuntu-latest
    name: Update APT metadata
    needs: [check-proton-versions, check-kv-caches, update-descriptors]
    # Run if:
    # 1. Descriptors were successfully updated (new packages available)
    # 2. OR versions differ between Proton API and APT cache (version mismatch)
    # 3. OR forced via input (can run even if update-descriptors was skipped)
    # IMPORTANT: !cancelled() allows this job to run even if update-descriptors was skipped
    if: |
      !cancelled() &&
      (
        needs.update-descriptors.result == 'success' ||
        needs.check-proton-versions.outputs.mail_version != needs.check-kv-caches.outputs.apt_mail_version ||
        needs.check-proton-versions.outputs.pass_version != needs.check-kv-caches.outputs.apt_pass_version ||
        inputs.force_apt
      )

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: whoami

      - name: Restore Proton API cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.PROTON_CACHE_DIR }}
          key: ${{ env.PROTON_CACHE_KEY }}

      - name: Ensure output directory
        run: mkdir -p ${{ env.APT_OUTPUT_DIR }}

      - name: Generate APT metadata
        run: pnpm ci:update-apt:generate
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROTON_CACHE_DIR: ${{ env.PROTON_CACHE_DIR }}
          APT_OUTPUT_DIR: ${{ env.APT_OUTPUT_DIR }}

      - name: Sign APT metadata with GPG
        run: pnpm ci:update-apt:sign
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          APT_OUTPUT_DIR: ${{ env.APT_OUTPUT_DIR }}

      - name: Cache APT metadata (for debugging)
        uses: actions/cache/save@v4
        with:
          path: ${{ env.APT_OUTPUT_DIR }}
          key: ${{ env.APT_CACHE_KEY }}

      - name: Verify APT metadata files
        run: |
          echo "🔍 Verifying APT metadata files..."
          ls -lh ${{ env.APT_OUTPUT_DIR }}
          echo ""
          echo "📄 Packages file preview (first 20 lines):"
          head -n 20 ${{ env.APT_OUTPUT_DIR }}/Packages || echo "⚠️  Packages file not found"
          echo ""
          echo "📋 Release file preview:"
          cat ${{ env.APT_OUTPUT_DIR }}/Release || echo "⚠️  Release file not found"
          echo ""
          echo "🔐 GPG-signed files:"
          [ -f "${{ env.APT_OUTPUT_DIR }}/InRelease" ] && echo "✅ InRelease found" || echo "⚠️  InRelease not found"
          [ -f "${{ env.APT_OUTPUT_DIR }}/Release.gpg" ] && echo "✅ Release.gpg found" || echo "⚠️  Release.gpg not found"
          [ -f "${{ env.APT_OUTPUT_DIR }}/public.gpg.key" ] && echo "✅ public.gpg.key found" || echo "⚠️  public.gpg.key not found"

      - name: Upload to Cloudflare KV
        run: pnpm ci:update-apt:upload "${{ env.APT_OUTPUT_DIR }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Summary
        run: |
          echo "✅ APT metadata updated"
          echo "📦 Proton Mail: ${{ needs.check-proton-versions.outputs.mail_version }}"
          echo "📦 Proton Pass: ${{ needs.check-proton-versions.outputs.pass_version }}"
          echo "📂 Output directory: ${{ env.APT_OUTPUT_DIR }}"
          echo "💾 Cached as: ${{ env.APT_CACHE_KEY }}"

  # ============================================================================
  # Future: RPM support (commented structure for future implementation)
  # ============================================================================
